title: PandaLED Docs
description: Documentation for the PandaLED project.
theme: just-the-docs
baseurl: ""
url: "https://derdeno.github.io/PandaLED"
repository: derDeno/PandaLED

permalink: pretty

defaults:
  - values:
      layout: "default"

exclude:
  # from https://github.com/jekyll/jekyll/blob/master/lib/site_template/_config.yml:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  # specific to the theme website:
  - README.md

# Site settings
logo: "/assets/icon.svg"

search_enabled: true
search:
  heading_level: 2
  previews: 2
  preview_words_before: 3
  preview_words_after: 3
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false
  focus_shortcut_key: "k"

enable_copy_code_button: true

# By default, consuming the theme as a gem leaves mermaid disabled; it is opt-in
mermaid:
  version: "9.1.6" # https://cdn.jsdelivr.net/npm/mermaid/

heading_anchors: true
aux_links:
  "PandaLED on GitHub":
    - "https://github.com/derDeno/PandaLED"

aux_links_new_tab: false
nav_enabled: true
nav_sort: case_sensitive
nav_external_links:
  - title: Web installer
    url: https://derdeno.github.io/PandaLED/web-installer.html

nav_error_report: true 
liquid:
  error_mode: strict
  strict_filters: true

back_to_top: true
back_to_top_text: "Back to top"

footer_content: 'Copyright &copy; 2024-2025 DNO. Distributed by an <a href="https://github.com/derDeno/PandaLED/tree/main/LICENSE">Creative Commons Attribution-NonCommercial-ShareAlike license.</a>'

last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

gh_edit_link: false
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/derDeno/PandaLED/"
gh_edit_branch: "gh-pages"
gh_edit_source: docs
gh_edit_view_mode: "tree"

color_scheme: nil

callouts_level: quiet
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

# Google Analytics Tracking (optional)
# ga_tracking: UA-2709176-10,G-5FG1HLH3XQ
# ga_tracking_anonymize_ip: true

plugins:
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-sitemap

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false