// @ts-check
const sidebars = {
  docs: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: [
        {type: 'autogenerated', dirName: 'getting-started'}
      ],
    },
    {
      type: 'category',
      label: 'API',
      link: {
        type: 'doc',
        id: 'api/introduction',
      },
      items: [
        {type: 'autogenerated', dirName: 'api'}
      ],
    }
  ],
  guides: [
    {
      type: 'category',
      label: 'Mappings',
      link: {
        type: 'doc',
        id: 'guides/mappings/introduction',
      },
      items: [
        {type: 'autogenerated', dirName: 'guides/mappings'},
      ],
    },
    {
      type: 'category',
      label: 'Setup Device',
      link: {
        type: 'generated-index',
        title: 'PandaLED Setup Device',
      },
      items: [
        {type: 'autogenerated', dirName: 'guides/setup-device'}
      ],
    },
    'guides/debugging',
    'guides/led-test-page',
  ],
};

export default sidebars;
